name: gtest

on:
  - push
  - pull_request

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Figure out version
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          COMMITS_SINCE_TAG=$(git rev-list ${TAG}..HEAD --count)
          if [ "${COMMITS_SINCE_TAG}" -eq 0 ]; then
            echo "VERSION=${TAG}" >> $GITHUB_ENV
          else
            echo "VERSION="$(git describe --tags --abbrev=8) >> $GITHUB_ENV
          fi
      - name: Cache Conan2 dependencies
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan2-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-conan2-
      - name: Set up Python 3.8 for gcovr
        uses: actions/setup-python@v4
      - name: SonarQube install
        uses: SonarSource/sonarcloud-github-c-cpp@v3
      - name: Install Conan
        run: pip install conan
      - name: Configure Conan Profile
        run: |
          conan profile detect -e
          conan remote add conan-nexus https://nexus.cridland.io/repository/dwd-conan --force
          conan remote login conan-nexus ci --password ${{ secrets.NEXUS_PASSWORD }}
      - name: Conan Deps (Debug)
        run: conan install . -s build_type=Debug -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Conan Deps (Debug)
        run: conan install . -s build_type=Debug -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Conan Deps (Release)
        run: conan install . -s build_type=Release -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Conan Deps (RelWithDebInfo)
        run: conan install . -s build_type=RelWithDebInfo -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Conan Deps (Debug+Tests)
        run: conan install . -o tests=True -s build_type=Debug -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: CMake tests
        run: cmake -B gh-build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES="conan_provider.cmake" -DCONAN_INSTALL_ARGS="-o=tests=True;--settings=compiler.cppstd=gnu23;--build=missing;--version=1.0.1-1"
      - name: Build
        run: cmake --build gh-build
      - name: Run Tests
        run: cd gh-build && ./sigslot-test
      - name: Create package (Debug)
        run: conan create . -s build_type=Debug -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Create package (Release)
        run: conan create . -s build_type=Release -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Create package (RelWithDebInfo)
        run: conan create . -s build_type=RelWithDebInfo -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Upload
        run: conan upload -r conan-nexus --confirm 'st-sigslot/*'
